### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Granipouss** [radiSaclay/radiServer#1]
Hey,

here is my review on [./routes/api/products.php](https://github.com/radiSaclay/radiServer/blob/023e6fa21b93e44a6f94dfd108fdfd020fa58cbd/routes/api/products.php)

- Use `'/api/products/{id}'` instead of `'/api/products/{primarykey}'`, shorter, clearer, better
- At line 16, `$args` is useless as the route has no parameter. Same on line 25.
- At line 41 and 55, no need to check if the arg is `null`, it's Slim's job to match the route only if the parameter has been given as it is not an optional parameter.
- Line 41 still, I'm not sure about the `new_` prefix before fields, it will be a pain for the mobile apps.

Btw, its also mobile apps' job to send proper data, so don't bother checking if all fields are valid. If needed, we will use [propel's validate behavior](http://propelorm.org/documentation/behaviors/validate.html), but mysql will send an error if a required field is empty.

**Comment by tiberiusferreira** [comment]
Hey,

I agree with all your remarks with exception of the last one: 

"Line 41 still, I'm not sure about the new_ prefix before fields, it will be a pain for the mobile apps."
Why would it be a problem for the mobile apps? 

Also, one of the reasons I wanted to do error checking ourselves instead of letting it escalate up to mysql was to prevent him from generating error logs for issues we already know how to prevent (such as a required field being empty). I think it will make it easier to detect real issues when they happen in the future since the log will be cleaner.

**Comment by Granipouss** [comment]
Well that mean that instead of using the field that have been defined in the schema, mobile app must add new_ to all their fields in the forms, but only the edit form and not the create one. Knowing that the create and edit form will likely identical in any other aspect. That is debatable tho' we may need to ask others what they think of it.

Checking is good, here ito is quite simple but in other cases you may have complex or numerous conditions to fulfill, remember that it is frontend duty to send only valid request, so that is double check in most cases. I'm just saying, don't waste too much effort on thathe, the bare minimum is fine
